zero initialize the recv structure on the stack
ipmitool/ipmitool pull request #314
Opened 2021-09-15 14:59 UTC by pstrinkle

This was caught via a sanitized build where the recv was used with stack data in some cases.

2021-11-03 07:54 UTC, AlexanderAmelkin requested changes

2021-11-03 07:54 UTC, AlexanderAmelkin commented on src/plugins/open/open.c
> +	struct ipmi_recv recv = {};
Good catch.
I see the same problem in `ipmievd.c:openipmi_read()`, would be nice to fix it there too.

2022-01-28 16:51 UTC, pstrinkle commented
I submitted the separate pull request to handle the other file.  Can we merge this?

2022-02-05 20:39 UTC, AlexanderAmelkin approved these changes

2022-02-05 20:40 UTC, merged