SEL printing: Invert the threshold inequality when an event is deasserted
ipmitool/ipmitool pull request #349
Opened 2022-07-25 13:24 UTC by andyclegg

The choice of `>` or `<` when printing the threshold inequality currently only depends on whether it is an upper or lower threshold. This is correct when the event is asserted, but when the event is deasserted the inequality is reversed and therefore the current code can give confusing results, e.g.:
```
 3cb | 07/17/2022 | 06:15:39 | Temperature ps1_inlet_temp | Upper Non-critical going high | Deasserted | Reading 43.94 > Threshold 44.88 degrees C
```
(Note `Reading 43.94 > Threshold 44.88`)

This PR fixes this by inverting the sign when the event is deasserted:

```
 3cb | 17/07/22 | 07:15:39 BST | Temperature ps1_inlet_temp | Upper Non-critical going high | Deasserted | Reading 43.94 < Threshold 44.88 degrees C
```

2022-07-29 15:13 UTC, andyclegg commented
@AlexanderAmelkin please could you approve the workflow for this PR?

2022-07-29 16:01 UTC, AlexanderAmelkin requested changes

2022-07-29 16:01 UTC, AlexanderAmelkin commented on lib/ipmi_sel.c
> +			bool ascending_threshold = (evt->sel_type.standard_type.event_data[0] & 0xf) % 2;
For consistency with the IPMI Specification I would suggest to call this `going_high`.

I know that the original code, aside from the variable, is not yours, but please update it
to no use raw magic numbers, such as `0xf` and `0`. There is already a macro for `0xf`,
and the `0` and `2` can be addressed with a comment, like this:

```
/* According to Table 29-6, Event Data byte 1 contains,
   among other info, the offset from the Threshold type code.
   According to Table 42-2, all even offsets are 'going low', and
   all odd offsets are 'going high' */
bool going_high = (evt->sel_type.standard_type.event_data[0]
                   & EVENT_OFFSET_MASK) % 2;
```
Other than this, it's all fine. Thanks for the change.

2022-08-01 07:59 UTC, andyclegg commented
Thanks for the helpful comments, I have updated the PR.

2022-08-05 10:34 UTC, andyclegg commented
Hi @AlexanderAmelkin - could this be merged now? Thanks

2022-08-05 15:56 UTC, AlexanderAmelkin approved these changes

2022-08-05 15:57 UTC, merged